randomize()
n = irandom(24)
if(n = 0) name1 = "Yol"
else if(n = 1) name1 = "Vah"
else if(n = 2) name1 = "Qel"
else if(n = 3) name1 = "Rev"
else if(n = 4) name1 = "Ram"
else if(n = 5) name1 = "Pob"
else if(n = 6) name1 = "Jel"
else if(n = 7) name1 = "Zig"
else if(n = 8) name1 = "Wahr"
else if(n = 9) name1 = "Kirl"
else if(n = 10) name1 = "Ulmh"
else if(n = 11) name1 = "Zov"
else if(n =12) name1 = "Drim"
else if(n =13) name1 = "Mals"
else if(n = 14) name1 = "Demos"
else if(n = 15) name1 = "Uriv"
else if(n = 16) name1 = "Olgo"
else if(n = 17) name1 = "Cah"
else if(n = 18) name1 = "Nel"
else if(n = 19) name1 = "Thur"
else if(n = 20) name1 = "Jah"
else if(n = 21) name1 = "Morn"
else if(n = 22) name1 = "Qua"
else if(n = 23) name1 = "Pom"
else if(n = 24) name1 = "Remo"


n = irandom(3)
if(n = 0) punc = ""
else if(n = 1) punc = "'"
else if(n = 2) punc = "-"
else punc = " "

n =  irandom(22)
if(n = 0) name2 = "Thul"
else if(n = 1) name2 = "Rohn"
else if(n = 2) name2 = "Delf"
else if(n = 3) name2 = "Wex"
else if(n = 4) name2 = "Varis"
else if(n = 5) name2 = "Kelm"
else if(n = 6) name2 = "Arim"
else if(n = 7) name2 = "Prax"
else if(n = 8) name2 = "Ceril"
else if(n = 9) name2 = "Meros"
else if(n = 10) name2 = "Limix"
else if(n = 11) name2 = "Xur"
else if(n = 12) name2 = "Yiras"
else if(n = 13) name2 = "Calrek"
else if(n = 14) name2 = "Mivas"
else if(n = 15) name2 = "Saggoz"
else if(n = 16) name2 = "Thago"
else if(n = 17) name2 = "Qina"
else if(n = 18) name2 = "Belruv"
else if(n = 19) name2 = "Higyar"
else if(n = 20) name2 = "Laurvim"
else if(n = 21) name2 = "Deuran"
else if(n = 22) name2 = "Melreik"


n = irandom(41) 

if(n = 0) sphere = "Blood"
else if(n = 1) sphere = "Peace"
else if(n = 2) sphere = "War"
else if(n = 3) sphere = "Vitality"
else if(n = 4) sphere = "the Harvest"
else if(n = 5) sphere = "Earth"
else if(n = 6) sphere = "Flames"
else if(n = 7) sphere = "Wind"
else if(n = 8) sphere = "Death"
else if(n = 9) sphere = "Fear"
else if(n = 10) sphere = "Happiness"
else if(n = 11) sphere = "Avarice"
else if(n = 12) sphere = "Alcohol"
else if(n = 13) sphere = "Pleasure"
else if(n = 14) sphere = "Luck"
else if(n = 15) sphere = "Friendship"
else if(n = 16) sphere = "Grudges"
else if(n = 17) sphere = "Justice"
else if(n = 18) sphere = "Sin"
else if(n = 19) sphere = "Intelligence"
else if(n = 20) sphere = "Corruption"
else if(n = 21) sphere = "Cooking"
else if(n = 22) sphere = "the Home"
else if(n = 23) sphere = "Time"
else if(n = 24) sphere = "Metal"
else if(n = 25) sphere = "Cinders"
else if(n = 26) sphere = "Ruin"
else if(n = 27) sphere = "Joy"
else if(n = 28) sphere = "the Sun"
else if(n = 29) sphere = "the Moon"
else if(n = 30) sphere = "Love"
else if(n = 31) sphere = "Food"
else if(n = 32) sphere = "Stupidity"
else if(n = 33) sphere = "Treason"
else if(n = 34) sphere = "Bigotry"
else if(n = 35) sphere = "the Heart"
else if(n = 36) sphere = "Light"
else if(n = 37) sphere = "Darkness"
else if(n = 38) sphere = "Storms"
else if(n = 39) sphere = "Poultry"
else if(n = 40) sphere = "Envy"
else if(n = 41) sphere = "Mistakes"


n = choose(0,1)
if(!n) gender = "God"
else gender = "Goddess"

blessed = choose(0,0,0,1)
if(!blessed) cursed = choose(0,0,0,1)

if(blessed) status = "Blessed by "
else if(cursed) status = "Scorned by "
else status = "Worships "

godDesc = status + string(name1) + string(punc) + string(name2) + ", " + gender + " of " + string(sphere) 
