if(file_exists("AethyrSave.sav")) file_delete("AethyrSave.sav")
ini_open("AethyrSave.sav")
ini_write_real("Save1","aethyrSpent",global.aethyrSpent)
ini_write_real("Save1","currAethyr",global.aethyr)
ini_write_real("Save1","hpMod",global.hpMod)
ini_write_real("Save1","mpMod",global.mpMod)
ini_write_real("Save1","attMod",global.attMod)
ini_write_real("Save1","mAttMod",global.mAttMod)
ini_write_real("Save1","hPotEff",global.hPotEffMod)
ini_write_real("Save1","mPotEff",global.mPotEffMod)
ini_write_real("Save1","enDiff",global.enDiffMod)
ini_write_real("Save1","hPotMax",player.mHPot)
ini_write_real("Save1","mPotMax",player.mMPot)
ini_write_real("Save1","runs",global.runs)
ini_write_real("Save1","kills",global.kills)
ini_write_real("Save1","alphBuild",global.build)
ini_write_real("Save1","hpCost",global.hpCost)
ini_write_real("Save1","mpCost",global.mpCost)
ini_write_real("Save1","attCost",global.attCost)
ini_write_real("Save1","mAttCost",global.mAttCost)
ini_write_real("Save1","hPotMaxCost",global.mHPotCost)
ini_write_real("Save1","mPotMaxCost",global.mMPotCost)
ini_write_real("Save1","upgradeTier",global.upgradeTier)
ini_write_real("Save1","aethyrCollected",global.aethyrCollected)
ini_write_real("Save1","critMod",global.critMod)
ini_write_real("Save1","critDmg",global.critDmg)
ini_write_real("Save1","critChncCost",global.critChncCost)
ini_write_real("Save1","critDmgCost",global.critDmgCost)
ini_write_real("Save1","hPotEffCost",global.hPotEffCost)
ini_write_real("Save1","mPotEffCost",global.mPotEffCost)
ini_write_real("Save1","golemDead",global.golemDead)
ini_write_real("Save1","banditDead",global.banditDead)
ini_write_real("Save1","sec",global.seconds)
ini_write_real("Save1","min",global.minutes)
ini_write_real("Save1","hr",global.hours)
ini_write_real("Save1","defMod",global.defMod)
ini_write_real("Save1","mDefMod",global.mDefMod)
ini_write_real("Save1","defCost",global.defCost)
ini_write_real("Save1","mDefCost",global.mDefCost)
str = ds_list_write(global.lastTen)
ini_write_string("Save1","lastTen",str)
ini_close()


